#!/bin/sh

git diff --cached --check || exit 1
for f in $(git diff --cached --name-only --diff-filter=ACM); do
    git show ":$f" | file --mime - | grep -q 'charset=[^[:space:]]*\(ascii\|utf-8\)' || continue
    [ -n "$(git show ":$f" | tail -c1)" ] || continue
    [ -z "$(git show HEAD:"$f" 2>/dev/null | tail -c1)" ] || continue
    echo "No EOL at EOF: $f" >&2
    exit 1
done
